Upgrade puppet-brewcask dependency
It looks like something has changed in the ecosystem. I started seeing
errors running `boxen`:

```
Error: Execution of 'brew boxen-latest brew-cask' returned 1: Error: No available formula with the name "brew-cask"
Error: /Stage[main]/Brewcask/Package[brew-cask]/ensure: change from absent to present failed: Execution of 'brew boxen-latest brew-cask' returned 1: Error: No available formula with the name "brew-cask"
```

And all of my `boxen::personal::osx_apps` would be skipped.

This change reflects the fact that `cask` now comes with `brew` now.