Fix `--silent` errors for `ibrarian-puppet`
Following an upgrade to git 2.14.1 I was getting the following error:

```
[Librarian] Git: /usr/bin/git
error: unknown option `silent'
usage: git version [<options>]

    --build-options       also print build options
```

Digging into this I found voxpupuli/librarian-puppet#52 which shows a
fix by including the latest `librarianp` gem. This fixes the issue for
me however more digging into the architecture of `librarian-puppet` will
be required to understand this issue better.